on:
  push:
    branches: [main]
  pull_request:
    types: [labeled, opened, synchronize, reopened, review_requested, ready_for_review]
  pull_request_review:
    types: [submitted]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  NIX_PATH: "nixpkgs=https://channels.nixos.org/nixpkgs-unstable/nixexprs.tar.xz"
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: wimpysworld/nothing-but-nix@main
      - uses: cachix/install-nix-action@v31
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - uses: actions/checkout@v6
      - run: nix develop . -c just -- ci

